-- Supabase SQL Editor에서 실행하세요.
create table if not exists public.absolute_pitch_scores (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(trim(nickname)) between 1 and 20),
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);
create index if not exists absolute_pitch_scores_ranking_idx on public.absolute_pitch_scores (score desc, created_at asc);
alter table public.absolute_pitch_scores enable row level security;
drop policy if exists "public read absolute pitch scores" on public.absolute_pitch_scores;
create policy "public read absolute pitch scores" on public.absolute_pitch_scores for select to anon,authenticated using (true);
drop policy if exists "public submit absolute pitch scores" on public.absolute_pitch_scores;
create policy "public submit absolute pitch scores" on public.absolute_pitch_scores for insert to anon,authenticated
  with check (score>=0 and char_length(trim(nickname)) between 1 and 20);
grant select,insert on public.absolute_pitch_scores to anon,authenticated;
grant usage,select on sequence public.absolute_pitch_scores_id_seq to anon,authenticated;

create table if not exists public.guitar_duel_rooms (
  code text primary key check (code ~ '^[A-Z0-9]{2,8}$'),
  status text not null default 'waiting' check (status in ('waiting','assigning','briefing','playing','finished')),
  tension integer not null default 29 check (tension between 0 and 100),
  starts_at timestamptz,
  ends_at timestamptz,
  winner text check (winner in ('attack','defend')),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create table if not exists public.guitar_duel_players (
  code text not null references public.guitar_duel_rooms(code) on delete cascade,
  token uuid not null,
  slot smallint not null check (slot in (1,2)),
  role text check (role in ('attack','defend')),
  primary key(code,token),
  unique(code,slot)
);
alter table public.guitar_duel_rooms enable row level security;
alter table public.guitar_duel_players enable row level security;
drop policy if exists "public read guitar duel rooms" on public.guitar_duel_rooms;
create policy "public read guitar duel rooms" on public.guitar_duel_rooms for select to anon,authenticated using (true);
grant select on public.guitar_duel_rooms to anon,authenticated;
revoke all on public.guitar_duel_players from anon,authenticated;

create or replace function public.guitar_duel_payload(p_code text,p_token uuid)
returns jsonb language sql security definer set search_path=public as $$
  select jsonb_build_object(
    'status','ok','role',(select role from public.guitar_duel_players where code=p_code and token=p_token),
    'room',(select to_jsonb(r) from public.guitar_duel_rooms r where code=p_code)
  )
$$;

create or replace function public.join_guitar_duel(p_code text,p_token uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c text:=upper(trim(p_code)); r public.guitar_duel_rooms; count_players int; begin
  if c !~ '^[A-Z0-9]{2,8}$' then return jsonb_build_object('status','invalid'); end if;
  insert into public.guitar_duel_rooms(code) values(c) on conflict(code) do nothing;
  select * into r from public.guitar_duel_rooms where code=c for update;
  if r.status='finished'
    or (r.status='waiting' and r.updated_at<now()-interval '10 minutes')
    or (r.status in ('assigning','briefing','playing') and r.ends_at<now()-interval '30 seconds') then
    delete from public.guitar_duel_rooms where code=c;
    insert into public.guitar_duel_rooms(code) values(c) returning * into r;
  end if;
  if exists(select 1 from public.guitar_duel_players where code=c and token=p_token) then return public.guitar_duel_payload(c,p_token); end if;
  select count(*) into count_players from public.guitar_duel_players where code=c;
  if count_players>=2 then return jsonb_build_object('status','full'); end if;
  insert into public.guitar_duel_players(code,token,slot) values(c,p_token,count_players+1);
  if count_players=1 then
    if random()<.5 then
      update public.guitar_duel_players set role=case slot when 1 then 'attack' else 'defend' end where code=c;
    else
      update public.guitar_duel_players set role=case slot when 1 then 'defend' else 'attack' end where code=c;
    end if;
    update public.guitar_duel_rooms set status='assigning',tension=29,starts_at=now()+interval '5 seconds',ends_at=now()+interval '15 seconds',updated_at=now() where code=c;
  end if;
  return public.guitar_duel_payload(c,p_token);
end $$;

create or replace function public.get_guitar_duel(p_code text,p_token uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c text:=upper(trim(p_code)); r public.guitar_duel_rooms; begin
  if not exists(select 1 from public.guitar_duel_players where code=c and token=p_token) then return null; end if;
  select * into r from public.guitar_duel_rooms where code=c for update;
  if r.status='assigning' and now()>=r.starts_at-interval '2.5 seconds' then update public.guitar_duel_rooms set status='briefing',updated_at=now() where code=c; end if;
  if r.status='briefing' and now()>=r.starts_at then update public.guitar_duel_rooms set status='playing',updated_at=now() where code=c; end if;
  if r.status='playing' and now()>=r.ends_at then update public.guitar_duel_rooms set status='finished',winner='defend',updated_at=now() where code=c; end if;
  return public.guitar_duel_payload(c,p_token);
end $$;

create or replace function public.act_guitar_duel(p_code text,p_token uuid,p_action text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c text:=upper(trim(p_code)); r public.guitar_duel_rooms; player_role text; delta int; begin
  select role into player_role from public.guitar_duel_players where code=c and token=p_token;
  if player_role is null then return null; end if;
  select * into r from public.guitar_duel_rooms where code=c for update;
  if r.status<>'playing' or now()>=r.ends_at then return public.get_guitar_duel(c,p_token); end if;
  if p_action='attack' and player_role='attack' then delta:=6;
  elsif p_action='defend' and player_role='defend' then delta:=-5;
  else return public.guitar_duel_payload(c,p_token); end if;
  update public.guitar_duel_rooms set tension=greatest(0,least(100,tension+delta)),
    status=case when tension+delta>=100 or tension+delta<=0 then 'finished' else status end,
    winner=case when tension+delta>=100 then 'attack' when tension+delta<=0 then 'defend' else winner end,updated_at=now()
    where code=c;
  return public.guitar_duel_payload(c,p_token);
end $$;

create or replace function public.finish_guitar_duel(p_code text,p_token uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c text:=upper(trim(p_code)); r public.guitar_duel_rooms; begin
  if not exists(select 1 from public.guitar_duel_players where code=c and token=p_token) then return null; end if;
  select * into r from public.guitar_duel_rooms where code=c for update;
  if r.status='playing' and now()>=r.ends_at then update public.guitar_duel_rooms set status='finished',winner='defend',updated_at=now() where code=c; end if;
  return public.guitar_duel_payload(c,p_token);
end $$;

create or replace function public.cleanup_guitar_duel(p_code text,p_token uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare c text:=upper(trim(p_code)); begin
  if exists(
    select 1 from public.guitar_duel_players p
    join public.guitar_duel_rooms r using(code)
    where p.code=c and p.token=p_token and r.status='finished'
  ) then
    delete from public.guitar_duel_rooms where code=c;
    return true;
  end if;
  return false;
end $$;

revoke all on function public.guitar_duel_payload(text,uuid),public.join_guitar_duel(text,uuid),public.get_guitar_duel(text,uuid),public.act_guitar_duel(text,uuid,text),public.finish_guitar_duel(text,uuid),public.cleanup_guitar_duel(text,uuid) from public;
grant execute on function public.join_guitar_duel(text,uuid),public.get_guitar_duel(text,uuid),public.act_guitar_duel(text,uuid,text),public.finish_guitar_duel(text,uuid),public.cleanup_guitar_duel(text,uuid) to anon,authenticated;
do $$ begin alter publication supabase_realtime add table public.guitar_duel_rooms; exception when duplicate_object then null; end $$;
