-- Independent, flexible band application system.
-- Existing ensemble tables are read only for the one-time initial snapshot below.

create table if not exists public.band_rounds (
  id bigint generated by default as identity primary key,
  name text not null check (btrim(name) <> ''),
  is_active boolean not null default false,
  song_application_open boolean not null default false,
  session_application_open boolean not null default false,
  is_blinded boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists band_rounds_one_active_idx
  on public.band_rounds (is_active)
  where is_active;

create table if not exists public.band_songs (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.band_rounds(id) on delete cascade,
  title text not null check (btrim(title) <> ''),
  artist text not null check (btrim(artist) <> ''),
  applicant_name text not null check (btrim(applicant_name) <> ''),
  student_id text not null check (btrim(student_id) <> ''),
  wanted_roles text[] not null default '{}',
  note text not null default '',
  is_formed boolean not null default false,
  source_song_id bigint unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists band_songs_round_created_idx
  on public.band_songs (round_id, created_at, id);

create table if not exists public.band_members (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.band_songs(id) on delete cascade,
  applicant_name text not null check (btrim(applicant_name) <> ''),
  student_id text not null check (btrim(student_id) <> ''),
  roles text[] not null default '{}',
  note text not null default '',
  is_included boolean not null default true,
  source_application_id bigint unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists band_members_song_created_idx
  on public.band_members (song_id, created_at, id);

create or replace function public.set_band_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists band_rounds_set_updated_at on public.band_rounds;
create trigger band_rounds_set_updated_at
before update on public.band_rounds
for each row execute function public.set_band_updated_at();

drop trigger if exists band_songs_set_updated_at on public.band_songs;
create trigger band_songs_set_updated_at
before update on public.band_songs
for each row execute function public.set_band_updated_at();

drop trigger if exists band_members_set_updated_at on public.band_members;
create trigger band_members_set_updated_at
before update on public.band_members
for each row execute function public.set_band_updated_at();

alter table public.band_rounds enable row level security;
alter table public.band_songs enable row level security;
alter table public.band_members enable row level security;

revoke all on public.band_rounds, public.band_songs, public.band_members from anon, authenticated;
grant select on public.band_rounds, public.band_songs, public.band_members to anon, authenticated;
grant insert (round_id, title, artist, applicant_name, student_id, wanted_roles, note)
  on public.band_songs to anon;
grant insert (song_id, applicant_name, student_id, roles, note)
  on public.band_members to anon;
grant all on public.band_rounds, public.band_songs, public.band_members to authenticated;
grant usage, select on public.band_rounds_id_seq, public.band_songs_id_seq, public.band_members_id_seq
  to anon, authenticated;

drop policy if exists "band rounds public read" on public.band_rounds;
create policy "band rounds public read"
on public.band_rounds for select
to anon, authenticated
using (true);

drop policy if exists "band songs public read" on public.band_songs;
create policy "band songs public read"
on public.band_songs for select
to anon, authenticated
using (true);

drop policy if exists "band members public read" on public.band_members;
create policy "band members public read"
on public.band_members for select
to anon, authenticated
using (true);

drop policy if exists "band songs public apply" on public.band_songs;
create policy "band songs public apply"
on public.band_songs for insert
to anon
with check (
  exists (
    select 1
    from public.band_rounds r
    where r.id = round_id
      and r.is_active
      and r.song_application_open
  )
);

create or replace function public.normalize_band_role(p_role text)
returns text
language sql
immutable
strict
set search_path = ''
as $$
  select case
    when regexp_replace(lower(btrim(p_role)), '\s+', '', 'g') ~ '^(보컬|vocal)[0-9]*$' then '보컬'
    when regexp_replace(lower(btrim(p_role)), '\s+', '', 'g') ~ '^(기타|guitar)[0-9]*$' then '기타'
    when regexp_replace(lower(btrim(p_role)), '\s+', '', 'g') ~ '^(베이스|bass)[0-9]*$' then '베이스'
    when regexp_replace(lower(btrim(p_role)), '\s+', '', 'g') ~ '^(키보드|건반|keyboard|key)[0-9]*$' then '키보드'
    when regexp_replace(lower(btrim(p_role)), '\s+', '', 'g') ~ '^(드럼|drum|drums)[0-9]*$' then '드럼'
    else btrim(p_role)
  end
$$;

grant execute on function public.normalize_band_role(text) to anon, authenticated;

drop policy if exists "band members public apply" on public.band_members;
create policy "band members public apply"
on public.band_members for insert
to anon
with check (
  exists (
    select 1
    from public.band_songs s
    join public.band_rounds r on r.id = s.round_id
    where s.id = song_id
      and r.is_active
      and r.session_application_open
      and cardinality(band_members.roles) > 0
      and not exists (
        select 1
        from unnest(band_members.roles) requested(role)
        where not exists (
          select 1
          from unnest(s.wanted_roles) wanted(role)
          where public.normalize_band_role(wanted.role) = public.normalize_band_role(requested.role)
        )
      )
  )
);

drop policy if exists "band rounds admin write" on public.band_rounds;
create policy "band rounds admin write"
on public.band_rounds for all
to authenticated
using ((select auth.jwt() ->> 'email') = 'kuagcku@gmail.com')
with check ((select auth.jwt() ->> 'email') = 'kuagcku@gmail.com');

drop policy if exists "band songs admin write" on public.band_songs;
create policy "band songs admin write"
on public.band_songs for all
to authenticated
using ((select auth.jwt() ->> 'email') = 'kuagcku@gmail.com')
with check ((select auth.jwt() ->> 'email') = 'kuagcku@gmail.com');

drop policy if exists "band members admin write" on public.band_members;
create policy "band members admin write"
on public.band_members for all
to authenticated
using ((select auth.jwt() ->> 'email') = 'kuagcku@gmail.com')
with check ((select auth.jwt() ->> 'email') = 'kuagcku@gmail.com');

create or replace function public.set_band_song_note(p_song_id bigint, p_note text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.band_songs s
  set note = coalesce(p_note, '')
  where s.id = p_song_id
    and exists (
      select 1
      from public.band_rounds r
      where r.id = s.round_id
        and r.is_active
    );

  if not found then
    raise exception 'Active band song not found';
  end if;
end;
$$;

revoke all on function public.set_band_song_note(bigint, text) from public;
grant execute on function public.set_band_song_note(bigint, text) to anon, authenticated;

-- Create the first band round from the newest regular ensemble round.
insert into public.band_rounds (name, is_active, song_application_open, session_application_open)
select er.name, true, false, false
from public.ensemble_rounds er
where er.type = 'regular'
order by er.created_at desc
limit 1
on conflict do nothing;

-- Copy the current song list once. Re-running this file does not duplicate it.
insert into public.band_songs (
  round_id, title, artist, applicant_name, student_id, wanted_roles, note,
  is_formed, source_song_id, created_at
)
select
  br.id, sa.title, sa.artist, sa.applicant_name, sa.student_id,
  coalesce(sa.sessions, '{}'), coalesce(sa.public_note, ''),
  coalesce(sa.is_formed, false), sa.id, sa.created_at
from public.song_applications sa
join public.ensemble_rounds er on er.id = sa.round_id
join public.band_rounds br on br.name = er.name and br.is_active
where er.id = (
  select id from public.ensemble_rounds
  where type = 'regular'
  order by created_at desc
  limit 1
)
and sa.status <> 'rejected'
on conflict (source_song_id) do nothing;

-- Closed rounds expose confirmed applicants only; preserve their exact timestamps.
insert into public.band_members (
  song_id, applicant_name, student_id, roles, source_application_id, created_at
)
select
  bs.id, app.applicant_name, app.student_id, coalesce(app.sessions, '{}'),
  app.id, app.created_at
from public.session_applications app
join public.band_songs bs on bs.source_song_id = app.song_id
where app.status = 'confirmed'
on conflict (source_application_id) do nothing;
